version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    hostname: localhost
    build: ./ # specify the directory of the Dockerfile
    image: haffydockerid/frontend
    ports:
      - "4200:80" # specify port forewarding

  express: #name of the second service
    build: server # specify the directory of the Dockerfile
    image: haffydockerid/backend
    ports:
      - "3000:3000" #specify ports forewarding